In [8]:
import csv 
import numpy as np 

In [9]:
try: #  to read the file and to avoid the case (file not found)
    with open ('HeartFailureDataset 1.csv','r')as csvFile:
        reader=list(csv.reader(csvFile,delimiter=","))
        header=list(reader[0])#to store the feature names
        other=np.array(reader[1:]) #to store the data
        other[other=='NA']=np.nan #to make the data cleaner 
except FileNotFoundError as error:
    print(error)

        
def task_2(male,female):
    '''Task 2 solution'''
    try:
        def gender():#This method return the “gender: with the lowest mean heart rate 
            if mean(male)<mean(female):
                return 'male'
            else:
                 return 'female'
        def mean(gender):#Calculate the median  
            return np.nanmean(gender)
        def std(gender):#Calculate the standard deviation
            return np.nanstd(gender)
        print(f'the mean for male is {mean(male):.4f}')
        print(f'the mean for female is {mean(female):.4f}')
        print(f'the std for male is {std(male):.4f}')
        print(f'the std for female is {std(female):.4f}')
        print(f'the lowest with mean  {min(mean(male),mean(female_hr)):.4f}is the {(gender())} ')
    except Exception as er:
        print('Task 2 has this error ', er)

def task_3(all_file):
    '''Task 3 solution'''
    try:

        def print_statistics(data):#better design 
            for i in range(1,50):
                print(f'{data[i-1]:.4f} {header[i]}')
                
        global the_median#We will use this in another method(task 6)
        the_median=np.nanmedian(all_file[0:,1:].astype(float),axis=0)
        the_q1=np.nanpercentile (all_file[0:,1:].astype(float),25,axis=0)
        the_q3=np.nanpercentile (all_file[0:,1:].astype(float),75,axis=0)
        iqr=the_q3-the_q1
        print(f'the median of all features is ')
        print(f'{print_statistics(the_median)}')
        print('********************************')
        print(f'the interquartile  of all features is')
        print(f'{print_statistics(iqr)}')
        print(f'the features of min iqr is {header[np.argmin(iqr)+1]}')
        print(f'the features of max iqr is {header[np.argmax(iqr)+1]}')
    except Exception as er:
        print('Task 3 has this error ', er)

def task_4(all_data):
    '''Task 4 solution'''
    try:
        def count(top_10):#to make it better design :)
            for i in range(0,10):
                print(f'{i+1}){top_10[i]}')
        global top_id #We will use this in another method(task 5)
        top_id=all_data[:,0]#store the id column 
        Systolic_blood_pressure=all_data[:,header.index('Systolic blood pressure')].astype(float)#store the Systolic blood pressure column
        Diastolic_blood_pressure=all_data[:,header.index('Diastolic blood pressure')].astype(float)# store the Diastolic blood pressure column
        total_blood_pressure = np.nansum([Systolic_blood_pressure, Diastolic_blood_pressure],axis=0)#the total blood pressure
        top_10_bp=np.argsort(total_blood_pressure)[::-1]#sort the total blood pressure (descending )
        top_10=top_id[top_10_bp[:10]]#fancy indexing to find the patient id 
        print(f' top 10 id  with the highest blood pressure values ')
        count(top_10)
    except Exception as er:
        print('Task 4 has this error ', er)
def task_5(all_data):
    '''Task 5 solution'''
    try:
        def count(top_10):#to make it better design :)
            for i in range(0,10):
                print(f'{i+1}){top_10[i]}')
        glucose=all_data[:,header.index('glucose')].astype(float)#store the glucose column
        remove_nan_from_glucose= glucose[np.logical_not(np.isnan(glucose))]#remove the np.nan 
        the_sorting=np.sort(remove_nan_from_glucose)[::-1]#sort the glucose (descending )
        top_10_glucous=np.argsort(remove_nan_from_glucose)[::-1]
        print(f'the patients in descending order based on their “glucose” is{the_sorting}')
        top_10=top_id[top_10_glucous[:10]]#fancy indexing to find the patient id 
        print(f'and the top 10 id bassed on glucose is ')
        count(top_10)
    except Exception as er:
        print('Task 5 has this error ', er)
    
def task_6(all_data):
    '''Task 6 solution'''
    try:
        Creatinine=all_data[:,header.index('Creatinine')].astype(float)#to store Creatinine column
        five_top_Creatinine=np.argsort(Creatinine)[-5:]#to sort id and store the top 5 only
        print('before ',all_data[[five_top_Creatinine],header.index('Creatinine')])#print the top 5 before 
        all_data[[five_top_Creatinine],header.index('Creatinine')]=the_median[header.index('Creatinine')-1]
        print('after ',all_data[[five_top_Creatinine],header.index('Creatinine')])#print the top 5 after
    except Exception as er:
        print('Task 6 has this error ', er)
def task_7(all_data):
    '''Task 7 solution'''
    try:
        def mean(data):#if the column all of it was nan it will return warning so :)
            for i in range(1,50):
                if np.all(np.isnan(data[:,i-1])):
                    print(np.nan,header[i])
                else:
                    print(f'{np.nanmean(data[:,i-1]):.4f} {header[i]}')
        top_100=np.argpartition(all_data[:,1:],-100,axis=0)[-100:]#to find the top 100 of each column
        top100_values=np.take_along_axis(all_data[:,1:],top_100,axis=0)
        mean_top_100=mean(top100_values.astype(float))# to calculate the mean for top 100 only (without the id column)
    except Exception as er:
        print('Task 7 has this error ', er)

def task_8(all_data):
    '''Task 8 solution'''
    try:
        Respiratory_rate=all_data[:,header.index('Respiratory rate')].astype(float)#to store the Respiratory rate column
        mean_Respiratory_rate=np.nanmean(Respiratory_rate)#the mean for Respiratory rate column
        std_Respiratory_rate=np.nanstd(Respiratory_rate)#the std for Respiratory rate column
        upper_limit=mean_Respiratory_rate+2*std_Respiratory_rate
        lower_limit=mean_Respiratory_rate-2*std_Respiratory_rate
        result=np.where((Respiratory_rate>upper_limit) | (Respiratory_rate< lower_limit))#the range between
        print('the patient IDs with 2 standard deviation away from the mean of “Respiratory rate” feature. ')
        print(all_data[result,0])
    except Exception as er:
        print('Task 8 has this error ', er)
def task_9(all_data):
    '''Task 9 solution'''
    try:
        other_withot_id=all_data[:,1:].astype(float)#remove id column
        dist = np.nansum((other_withot_id[:, np.newaxis, :] - other_withot_id[np.newaxis, :, :]) ** 2, axis=-1)#compute the distance between each pair of points. Recall that the squared-distance between two points is the sum of the squared differences in each dimension
        K = 3
        nearest_partition = np.argpartition(dist, K + 1, axis=1)
        print('k-nearestneighbors, where k = 3, for each patient are')
        print(nearest_partition)
    except Exception as er:
        print('Task 2 has this error ', er)
    
def task_10(all_data):
    '''Task 10 solution'''
    try:
        patients_data = all_data[:,1:].astype(float)#to store the data without id column
        correlation_matrix = np.corrcoef(patients_data, rowvar=True)#to find correlation of each two patients
        np.fill_diagonal(correlation_matrix, -1)#the diagonal should be zeroes
        max_matrix_index = np.unravel_index(np.nanargmax(correlation_matrix), correlation_matrix.shape)#max two correlation indexes
        max_matrix_value = correlation_matrix[max_matrix_index]#max correlation value
        patient_pair = (max_matrix_index[0], max_matrix_index[1])#to find the pair of it
        print(f'the pair of patients with the highest correlation coefficient ({max_matrix_value:.4f}): {patient_pair}')
    except Exception as er:
        print('Task 2 has this error ', er)


    



In [10]:
male_hr=other[:,header.index('heart rate')][other[:,header.index('gendera')].astype(int)==1].astype(float)
female_hr=other[:,header.index('heart rate')][other[:,header.index('gendera')].astype(int)==2].astype(float)
task_2(male_hr,female_hr)

the mean for male is 84.8073
the mean for female is 84.3678
the std for male is 16.0721
the std for female is 15.9546
the lowest with mean  84.3678is the female 


In [11]:
task_3(other)


the median of all features is 
0.0000 outcome
77.0000 age
2.0000 gendera
28.3125 BMI
1.0000 hypertensive
0.0000 atrialfibrillation
0.0000 CHD with no MI
0.0000 diabetes
0.0000 deficiencyanemias
0.0000 depression
0.0000 Hyperlipemia
0.0000 Renal failure
0.0000 COPD
83.6108 heart rate
116.1282 Systolic blood pressure
58.4615 Diastolic blood pressure
20.3723 Respiratory rate
36.6508 temperature
96.4523 SP O2
1675.0000 Urine output
30.8000 hematocrit
3.4900 RBC
29.7500 MCH
32.9857 MCHC
90.0000 MCV
15.5062 RDW
9.6800 Leucocyte
222.6667 Platelets
82.4667 Neutrophils
0.3000 Basophils
10.4750 Lymphocyte
14.6333 PT
1.3000 INR
5840.0000 NT-proBNP
89.2500 Creatine kinase
1.2875 Creatinine
30.6667 Urea nitrogen
136.4000 glucose
4.1154 Blood potassium
139.2500 Blood sodium
8.5000 Blood calcium
102.5000 Chloride
13.6667 Anion gap
2.0923 Magnesium ion
7.3800 PH
26.5000 Bicarbonate
1.6000 Lactic acid
43.0000 PCO2
55.0000 EF
None
********************************
the interquartile  of all features is
0.

In [12]:
task_4(other)

 top 10 id  with the highest blood pressure values 
1)178001
2)163199
3)190823
4)196856
5)118932
6)169263
7)189112
8)196981
9)184453
10)114085


In [13]:
task_5(other)

the patients in descending order based on their “glucose” is[414.1        369.         365.75       ...  70.22222222  69.1
  66.66666667]
and the top 10 id bassed on glucose is 
1)126474
2)168835
3)109401
4)143304
5)138444
6)149947
7)190669
8)145935
9)165271
10)192823


In [14]:
task_6(other)

before  [['9.0125' '9.2' '12.45' '12.8375' '15.52727273']]
after  [['1.2875' '1.2875' '1.2875' '1.2875' '1.2875']]


In [15]:
task_7(other)

1.0000 outcome
90.3700 age
2.0000 gendera
nan BMI
1.0000 hypertensive
1.0000 atrialfibrillation
1.0000 CHD with no MI
1.0000 diabetes
1.0000 deficiencyanemias
1.0000 depression
1.0000 Hyperlipemia
1.0000 Renal failure
0.8900 COPD
97.8705 heart rate
98.2882 Systolic blood pressure
82.5394 Diastolic blood pressure
29.2353 Respiratory rate
37.9539 temperature
99.5424 SP O2
911.7500 Urine output
43.4354 hematocrit
4.9558 RBC
33.8099 MCH
35.1965 MCHC
97.9929 MCV
20.8041 RDW
9.5737 Leucocyte
311.2113 Platelets
nan Neutrophils
nan Basophils
nan Lymphocyte
38.1894 PT
3.9873 INR
6365.3000 NT-proBNP
nan Creatine kinase
4.3980 Creatinine
69.0474 Urea nitrogen
95.3088 glucose
5.0796 Blood potassium
145.5885 Blood sodium
9.4395 Blood calcium
99.3821 Chloride
15.2180 Anion gap
2.6676 Magnesium ion
nan PH
37.6947 Bicarbonate
nan Lactic acid
nan PCO2
70.1200 EF


In [16]:
task_8(other)

the patient IDs with 2 standard deviation away from the mean of “Respiratory rate” feature. 
[['127360' '191289' '116888' '113812' '138440' '190054' '153366' '116367'
  '133975' '152960' '145790' '108084' '107777' '126474' '107462' '141222'
  '130354' '128899' '180135' '173649' '151364' '154468' '155273' '109577'
  '153207' '166585' '155044' '110347' '120626' '128969' '133499' '192198'
  '110335' '175630' '166387' '149010' '196357' '161407' '184331' '145202'
  '102433' '111327' '123701' '145333' '150871' '111573' '126717' '161037'
  '180744' '145248' '113009' '182813' '146160' '159785']]


In [17]:
task_9(other)

k-nearestneighbors, where k = 3, for each patient are
[[ 875    0  835 ... 1174 1175 1176]
 [   1  959   27 ... 1174 1175 1176]
 [   2  735 1013 ... 1174 1175 1176]
 ...
 [1174  817  816 ...    7    3  588]
 [ 822 1176  919 ...    7    3  588]
 [ 558 1176  643 ...    7    3  588]]


In [18]:
task_10(other)

the pair of patients with the highest correlation coefficient (1.0000): (17, 846)
